# Generated by Django 4.2.16 on 2024-10-03 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0004_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='client',
        ),
        migrations.DeleteModel(
            name='TreatmentService',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
