# Generated by Django 4.2.16 on 2025-01-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0006_remove_profile_address_appointment_appointment_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
    ]
