# Generated by Django 4.2.16 on 2025-01-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0007_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
